name: Vite Build and Deploy

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # Allows workflow to push changes to the repository
  id-token: write # Ensure this permission is included
  pages: write # Required for deploying to GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for your job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Set the Node.js version (adjust as necessary)

      - name: Install dependencies
        run: npm install # Install dependencies using npm

      - name: Set environment variables from secrets
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
          # Add more secrets as necessary

      - name: Build with Vite
        run: npm run build # Run the build script defined in your package.json

      # Upload the build output as an artifact
      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist # Adjust this if your build output is in a different folder

      # Deploy the build output to GitHub Pages
      - name: Deploy on Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication
